
i:
	rlwrap sml utils.sig utils.sml \
	           stream.sig \
             stringstream.sml \
             liststream.sml \
             parscomb.sig parscomb.sml \
             lexer.sig lexer.sml \
             parser.sig parser.sml \
             typecheck.sig typecheck.sml

